title: Nexus Language
author: Satoru Kawahara
description: A LLM-friendly language
url: "https://nymphium.github.io"
repository: "https://github.com/Nymphium/Nexus"
google_analytics:
encoding: "utf-8"
future: true
theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
